name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o codigo
      uses: actions/checkout@v4.2.2
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    -  name: Buildando image e enviando para o docker hub
       uses: docker/build-push-action@v6
       with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
          leandromelo99/aula-primeira-pipeline:v${{github.run_number}}
          leandromelo99/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: ["CI"]
    steps:
    - name: Obtendo o codigo
      uses: actions/checkout@v4.2.2
    - name: Configuração de contexto do kube config
      uses: azure/k8s-set-context@v4.0.0
      with:
       method: kubeconfig
       kubeconfig: ${{secrets.K8S_CONFIG}}
    - name: Execução do manifesto
      uses: Azure/k8s-deploy@v5
      with:
       namespace: 'myapp'
       manifests: |
         ./k8s/deployment.yaml
       images: |
        'leandromelo99/aula-primeira-pipeline:v${{github.run_number}}'